### ISSUE TITLE
Cannot run CEVAE model with GPU

### ISSUE THREAD

**Issue by xiaogangzhu** [pyro-ppl/pyro#3263] opened 2023-08-22 02:40 UTC
### Issue Description
Provide a brief description of the issue.
Hi, I am trying to run the synthetic script under CEVAE tutorial, when I set cuda = True it fail with following error.
```
INFO     Training with 10 minibatches per epoch
Traceback (most recent call last):
  File "synthetic.py", line 108, in <module>
    main(args)
  File "synthetic.py", line 64, in main
    cevae.fit(
  File "/home/tstone10/anaconda3/envs/causal-ml/lib/python3.8/site-packages/pyro/contrib/cevae/__init__.py", line 590, in fit
    for x, t, y in dataloader:
  File "/home/tstone10/anaconda3/envs/causal-ml/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/tstone10/anaconda3/envs/causal-ml/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 676, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/home/tstone10/anaconda3/envs/causal-ml/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 623, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/tstone10/anaconda3/envs/causal-ml/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 254, in __iter__
    for idx in self.sampler:
  File "/home/tstone10/anaconda3/envs/causal-ml/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 132, in __iter__
    yield from torch.randperm(n, generator=generator).tolist()
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'

```
So I cannot use GPU to train CEVAE. Can someone helps?

### Environment
For any bugs, please provide the following:
 - OS and python version.
 Linux  python==3.8
 - PyTorch version, or if relevant, output of `pip freeze`.
 2.0.1
 - Pyro version: output of `python -c 'import pyro; print pyro.__version__'`
1.8.6

### Code Snippet
Provide any relevant code snippets and commands run to replicate the issue.

**Comment by xiaogangzhu** [comment] 2023-08-23 07:44
Not working too

**Comment by martinjankowiak** [comment] 2023-08-23 15:37
works for me on the dev branch. what versions of pyro/torch are you using?

```
python examples/cvae/main.py --cuda
NN Epoch 0 train    :   9%|██▋                             | 40/469 [00:03<00:15, 27.54it/s, early_stop_count=0, loss=178.30]
```
this is with torch==1.13.0+cu116

**Comment by xiaogangzhu** [comment] 2023-08-24 02:55
Hi, I also use the dev branch but the model is cevae not cvae, the file is at /examples/contrib/cevae/synthetic.py

**Comment by martinjankowiak** [comment] 2023-08-24 15:10
@xiaogangzhu ok i can reproduce your issue and [this PR](https://github.com/pyro-ppl/pyro/pull/3264) seems to fix it

this looks like a pytorch issue because the docstrings of `DataLoader` do not seem to suggest that passing a `generator` like this is required. might be worth checking with pytorch if this is a known issue and/or if it's been fixed in later versions

**Comment by xiaogangzhu** [comment] 2023-08-25 08:25
Hi, I saw the fixed in Dataloader function
```
 dataloader = DataLoader(
            dataset,
            batch_size=batch_size,
            shuffle=True,
            generator=torch.Generator(device=x.device),
        )
```
Thanks very much! But another problem is that when I am running the script I cannot set num_workers to improve my data loading speed just like what I usually do in pytorch. Is there any way to fix this?

**Comment by martinjankowiak** [comment] 2023-08-25 14:53
@xiaogangzhu this is meant to be an example pyro script not full service software with every conceivable functionality. if you want to add new features to support your use case you'll need to fork the script. 

thanks for reporting the GPU issue!

**Closed by martinjankowiak** 2023-08-25 14:53 UTC
Labels: bug
